from enum import StrEnum


class ClaimStatus(StrEnum):
    DRAFT = "DRAFT"
    RECEIPT_UPLOADED = "RECEIPT_UPLOADED"
    OCR_COMPLETED = "OCR_COMPLETED"
    VERIFIED = "VERIFIED"
    ADDITIONAL_PROOF_REQUIRED = "ADDITIONAL_PROOF_REQUIRED"
    ADDITIONAL_PROOF_UPLOADED = "ADDITIONAL_PROOF_UPLOADED"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    REJECTED = "REJECTED"


class DocumentType(StrEnum):
    ACADEMY_RECEIPT = "ACADEMY_RECEIPT"
    CARD_STATEMENT = "CARD_STATEMENT"


class FinalResult(StrEnum):
    MATCHED = "MATCHED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    REJECTED = "REJECTED"
